### ISSUE TITLE
php7.1.1rc1下运行报错

### ISSUE THREAD

**Issue by lonycc** [shooyaaa/v2ex#1]
```
$ php v2ex.php
V2ex for shell
         nodes
PHP Fatal error:  Uncaught InvalidArgumentException: Expecting a DOMNodeList or
DOMNode instance, an array, a string, or null, but got "boolean". in F:\myjob\ph
p\v2ex\vendor\symfony\dom-crawler\Crawler.php:120
Stack trace:
#0 F:\myjob\php\v2ex\vendor\symfony\dom-crawler\Crawler.php(67): Symfony\Compone
nt\DomCrawler\Crawler->add(false)
#1 F:\myjob\php\v2ex\v2ex.php(49): Symfony\Component\DomCrawler\Crawler->__const
ruct(false)
#2 F:\myjob\php\v2ex\v2ex.php(147): V2ex->listPost()
#3 F:\myjob\php\v2ex\v2ex.php(185): V2ex->printAllNode()
#4 F:\myjob\php\v2ex\v2ex.php(181): V2ex->outputNodeAndPost()
#5 F:\myjob\php\v2ex\v2ex.php(209): V2ex->help()
#6 {main}
  thrown in F:\myjob\php\v2ex\vendor\symfony\dom-crawler\Crawler.php on line 120


Fatal error: Uncaught InvalidArgumentException: Expecting a DOMNodeList or DOMNo
de instance, an array, a string, or null, but got "boolean". in F:\myjob\php\v2e
x\vendor\symfony\dom-crawler\Crawler.php:120
Stack trace:
#0 F:\myjob\php\v2ex\vendor\symfony\dom-crawler\Crawler.php(67): Symfony\Compone
nt\DomCrawler\Crawler->add(false)
#1 F:\myjob\php\v2ex\v2ex.php(49): Symfony\Component\DomCrawler\Crawler->__const
ruct(false)
#2 F:\myjob\php\v2ex\v2ex.php(147): V2ex->listPost()
#3 F:\myjob\php\v2ex\v2ex.php(185): V2ex->printAllNode()
#4 F:\myjob\php\v2ex\v2ex.php(181): V2ex->outputNodeAndPost()
#5 F:\myjob\php\v2ex\v2ex.php(209): V2ex->help()
#6 {main}
  thrown in F:\myjob\php\v2ex\vendor\symfony\dom-crawler\Crawler.php on line 120
```

**Comment by lonycc** [comment]
v2ex反爬策略生效，抓首页什么都没获取到。
